feat: smartd without root .msmtprc

diff --git a/2root.smartd/usr/local/bin/smartdnotify b/2root.smartd/usr/local/bin/smartdnotify
--- a/2root.smartd/usr/local/bin/smartdnotify
+++ b/2root.smartd/usr/local/bin/smartdnotify
@@ -1,15 +1,13 @@
-#! /usr/bin/env sh
-#
+#!/usr/bin/env bash
+
+# Check for internet connectivity
 if ! ping -c1 www.google.com > /dev/null 2>&1; then
 	sleep 30
 fi
-# Send mail
-#echo "$SMARTD_MESSAGE" | mail -s "$SMARTD_FAILTYPE $HOSTNAME" "$SMARTD_ADDRESS"
-#Device:$SMARTD_DEVICE Device node:$SMARTD_DEVICESTRING
-#$HOSTNAME smartd has detected $SMARTD_FAILTYPE error on $SMARTD_DEVICE
-sendmail -t << EOF
-To: danielepietroarosio@gmail.com
-Subject: SMART error ($SMARTD_FAILTYPE) detected on host: $(hostname)
+
+# Prepare email content
+EMAIL_BODY="To: danielepietroarosio@gmail.com
+Subject: SMART error ($SMARTD_FAILTYPE) detected on host: $HOSTNAME
 
 $SMARTD_MESSAGE
 
@@ -17,10 +15,15 @@ Date occurred:	$SMARTD_TFIRST
 
 # Full message
 $SMARTD_FULLMESSAGE
-EOF
+"
+
+# Send mail
+if ! echo "$EMAIL_BODY" | sudo -u dan DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus -i sendmail -t; then
+	echo "Failed to send email"
+	exit 1
+fi
 
 # Notify user
-if [ -f /usr/bin/notify-send ]
-then
+if [ -f /usr/bin/notify-send ]; then
   sudo -u dan DISPLAY=:0 DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus notify-send "S.M.A.R.T Error ($SMARTD_FAILTYPE)" "$SMARTD_MESSAGE" --icon=dialog-warning
 fi
